OPTS+=" --without-kerberos     \
        --with-dpms-ext        \
        --with-xf86vmode-ext   \
        --with-xf86gamma-ext   \
        --with-proc-interrupts \
        --with-pthread         \
        --with-xshm-ext        \
        --enable-locking" &&

OPTS+=" --without-pixbuf"

default_build
